apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://istio-release.storage.googleapis.com/charts
    chart: istio
    targetRevision: 1.26.2
    helm:
      releaseName: istio
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
