apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    chart: jaeger
    targetRevision: 3.4.1
    helm:
      releaseName: jaeger
      insecureSkipTLSVerify: true
      values: |
        provisionDataStore:
          cassandra: false
          elasticsearch: false
          kafka: false
        collector:
          enabled: true
          service:
            ports:
              - name: zipkin
                port: 9411
                protocol: TCP
                targetPort: zipkin
        agent:
          enabled: true
        query:
          enabled: true
        storage:
          type: memory
        ingress:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
