apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/szabobalazs2003/argocd-test
    path: k8s
    targetRevision: istio2
  destination:
    server: https://kubernetes.default.svc
    namespace: app1
  syncPolicy:
    syncOptions:
      - Createnamespace=true